### ISSUE TITLE
Iterables subclassing does not work properly with mypy 

### ISSUE THREAD

**Issue by deusebio** [CGnal/cgnal-core#16]
At the present point, we can subclass BaseIterable class into more specific List of objects, such as Iterables of Documents or Samples. However when we subclass these, we may want to extend their cached and lazy representation too. See for instance adding "to_df" methods to CachedDocuments. 

This is achieved by re-implementing the properties __lazyType__ and __cachedType__, see [here](https://github.com/CGnal/cgnal-core/blob/3764742323b0ed8dc5d90b34d8ff1bfdd67618d6/cgnal/core/data/model/core.py#L139). If this work when the code runs, this does not comply with mypy. In fact, 

```
docs: CachedDocuments = CachedDocuments([Document("my-id", dict())])

reveal_type(docs.map(lambda x: x))  # LazyIterable while it should be LazyDocuments`
```

In order to do this, re-handling of generics and typing for Iterable should be reviewed and changed

**Comment by NicolaDonelli** [comment]
Uhm, I wonder if this problem could not be solved by a simple overload of the problematic methods in the child class...

**Comment by deusebio** [comment]
Not really. This requires overloading "all" methods of BaseIterable (map, filter, take, etc) to better specify the output type. Avoiding this is the reason why we factored out the lazyType and cacheType to be used within the method of BaseIterable. 

The solution I'm working on is based on making the BaseIterable generic with respect to three classes:
* The type of elements it includes
* the cached iterable type
* the lazy iterable type

**Comment by NicolaDonelli** [comment]
Actually, I was thinking about overloading these methods in the child classes, not in BaseIterable, according to the types required by the child class.

**Comment by deusebio** [comment]
But again, this requires to redefine all the methods, doesn't it? I'm about to open a PR by today to explain a bit better what I mean

**Comment by deusebio** [comment]
For sake of clarity, I'll try to be more specific, hoping this will clarify the issue and the approach taken in the PR. I'll apply this only to `map`, but this can be easily extended to the other methods of BaseIterable. 

As of today, the implemantion of `map` in BaseIterable is

```
def map(self, f: Callable[[T], T_co]) -> "LazyIterable[T_co]":
    def generator():
        for item in self:
            yield f(item)

    return self.__lazyType__(IterGenerator(generator))
```
 
where `self.__lazyType__ ` is

```
@property
def __lazyType__(self) -> "Type[LazyIterable]":
    return LazyIterable 
```

When we subclass other special iterable, such as `Documents`, we only redefine the `__lazyType__` property, while all other methods (such as map) are inherited, e.g. 

```
class Documents(BaseIterable[Document]):
    @property
    def __lazyType__(self) -> "Type[LazyDocuments]":
        return LazyDocuments
```

While this works at runtime

```
docs: CachedDocuments = CachedDocuments([Document("my-id", dict())])

type(docs.map(lambda x: x))  #LazyDocuments as expected
```

the typing is not quite right

```
reveal_type(docs.map(lambda x: x))  # LazyIterable
```

due to the fact that the signature of map is indeed

```
def map(self, f: Callable[[T], T_co]) -> "LazyIterable[T_co]"
```

I don't think that overloading map in the `Documents` class is a feasible option (as it would actually mean overloading all methods of BaseIterable...). The solution that can be found in the PR, achieve the desired result using generics and defining the BaseIterable as follows:

```
class BaseIterable(Generics[T, L]):
    def map(self, f: Callable[[T], T_co]) -> L: ...
```
When subclassing Documents we then specify both types:

```
class Documents(BaseIterable[Documents, LazyDocuments]):
    ...
```

Hope this clarifies the need and the proposed implementation.

**Comment by NicolaDonelli** [comment]
Ok, now I got it. But still, this requires implementing three more private classes to handle the typing. Is this really less "code expensive" than overloading the methods where needed?

**Comment by deusebio** [comment]
It is surely more general and bug free: what if we were to add a method to the BaseIterable class (e.g. reduce, collect, etc)? What if you forgot to overload one of the methods of BaseIterable, while extending a class? 

Honestly, I don't believe overloading methods would be a robust and reliable solution, but I'd love to hear also @nromeoarena opinion

**Comment by nromeoarena** [comment]
I prefer the Enrico's solution, we have already discuss on it, the use of Generics makes code more robust and type safe (that I consider very important item), and in an elegant way (from my point of view).

**Comment by NicolaDonelli** [comment]
The robustness does not come from overloading but from type checking: if one forgets to overload any given method the type checker should highlight it (after all, the fact that the type-checker raises some issues in case of not-overloaded methods is the whole point of this issue, isn't it?).
