### ISSUE TITLE
Only concrete class can be given where "Type[Metric]" is expected

### ISSUE THREAD

**Issue by afalcioni** [CGnal/cgnal-core#25]
There is a typing problem in _cgnal/analytics/ml/core/__init__.py_ in the definition of the `Metric` class:

`error: Only concrete class can be given where "Type[Metric]" is expected`

I believe the problem occurs when calling `type(self)`.

**Comment by NicolaDonelli** [comment]
Why is this issue here if it referred to cgnal.analytics?
