### ISSUE TITLE
pytest returns a wrong coverage when no argument is passed

### ISSUE THREAD

**Issue by Gioia92** [CGnal/cgnal-core#37]
When pytest is called without an argument it returns a coverage grater than one even when tests are not run. To solve this issue it is sufficient to add the name of the folder containing the tests as an argument to pytest in Makefile:

${PYTHON} -m pytest tests

**Comment by NicolaDonelli** [comment]
The correction is easy but it would be interesting to understand what exactly pytest parses when no argument is passed...
