### ISSUE TITLE
Circular dependency worth it or not

### ISSUE THREAD

**Issue by deusebio** [CGnal/cgnal-core#39]
While working on PR #38 , I have been looking deeper into a circular dependency we have. Things work so-far but I don't know if there is a better way to do this, and how we could change the behaviour. 

At the moment, we have a [class](https://github.com/CGnal/cgnal-core/blob/main/cgnal/core/data/model/core.py#L232) (or a trait, or an interfact) that implements once for all methods like map, foreach, filter. This class is called IterableUtils. However, since it wants to be generic with respect to lazy-class and cached-class implementations, this class allow the definition of the lazy and cached implementation, while implementing the other methods. 

This is nice, since we can do something like

```
CachedIterable([...]).map(f)   # This is a LazyIterable
CachedDataset([...]).map(f)   # This is a LazyDataset
LazyDocuments([...]).map(f)   # This is a LazyDocuments
```

and thus keeping the types consistent, without the need of re-implementing the map method.

However, a problem of circular dependency arises, since we want all Cached and Lazy class to inherit from IterableUtils (such that they all have map, filter, foreach, etc), but the IterableUtils of this class need the definition of Cached* and Lazy*. 

This circular dependency should be clear from the implementation of [BaseIterable](https://github.com/CGnal/cgnal-core/blob/main/cgnal/core/data/model/core.py#L337), [CachedIterable](https://github.com/CGnal/cgnal-core/blob/main/cgnal/core/data/model/core.py#L337) and [LazyIterable](https://github.com/CGnal/cgnal-core/blob/main/cgnal/core/data/model/core.py#L369). 

The circular dependency is however prevented by making the references to CacheIterable and LazyIterable in IterableUtils a property, and therefore executed only when calling the methods and not at class definition. Making these properties a class attribute is however impossible (and this would lead to infinite recursion)

If in one hand I like the behaviour we have with map, filter and foreach (that are only implemented once), I really don't like the circularity in this. 

I'm curious on what others think? Especially those coming from other programming langauges? @aiola @nromeoarena

**Comment by aiola** [comment]
My suggestion would be to use python Mixin classes. I implemented a possible solution of this kind: https://github.com/CGnal/cgnal-core/compare/main...wip-fix-generic-iterables (probably better to look at the plain code rather than looking at the diff).

**Comment by nromeoarena** [comment]
I like the @aiola solution, could be the right way

**Comment by deusebio** [comment]
Thanks @aiola for the suggestion. I've taken a look at the code. I try to recap the modifications on these bullet points (with small comments):

1. *Usage of mixin classes*. I totally agree and like to use mixing (a bit like Traits in scala) and that the old _IterableUtils => new IterableMixing is missing inheritance from BaseIterable, which is not required nor useful. 
2. *swap from properties to init to define type for the mixin class.* => I don't see any advantage to do this, and actually I believe this makes the code a bit convoluted and bug-prone (we have to remember to call this method within the init method of the child classes. On the other hand, if we were to use abstract properties, python would raise errors)
3. *Removal of one abstraction level*: e.g. Documents that has two subclasses: CachedDocuments and LazyDocuments. I personally like to have an abstraction whose implementation can be cached or lazy, as I could implement a method irrespective if the object is cached or lazy as long as I use the IterableMixin functionalities. 

From my understanding, In order to "remove" circular dependencies, of all 3 points, only 3) is strictly required (since we actually remove the class that makes things circular). It depends what we value more I suppose. But also with the proposed solution we cannot do what I consider an issue with the current implementation that is

> Making these properties a class attribute is however impossible (and this would lead to infinite recursion)

Also in this case, we can access to the type of the output of the methods map, filter, etc **only** after creating an instance of the class (since this is in the init method). But, I suppose there is no solution to this (as the problem is circular on its own: the CachedIterable is a class that has an attribute which is a CachedIterable...)

**Comment by aiola** [comment]
Ok, now I understand the issue a bit better.

Actually it is possible to use class attributes, but we need to resort to some python "sorcery". See updates in the same branch.

Regarding the intermediate abstraction level provided by the `Documents` class, it can be easily reinstated. I removed it because in this implementation it would be empty. If there is need to have a common interface between the lazy and cached versions we can put it back.

**Comment by deusebio** [comment]
Nice @aiola! I've seen the code. It uses quite a bit of tricks (with decorators and a tiny bit of mutability) but it indeed achieve the goal of having a class that fully wrap its business logic when it comes to cache and lazy types, with no need to instaciate objects

To be honest, I really don't mind. I mean, although under the hood we use some tricks, the API to extend these classes is actually rather concise. 

About `Documents`, I suppose one common feature is that it is a `IterableMixing[Document, LazyDocument, CachedDocument]`,  

```
class Documents(IterableMixing[Document, LazyDocument, CachedDocument]):
    pass

class CachedDocuments(Documents, CachedIterable[Document])
    pass

class LazyDocuments(Documents, LazyIterable[Document])
    pass
```

BTW, while reviewing the latest version, I realized that I was wrong when I said that `IterableMixing` does not need any inheritance from `BaseIterable`. Actually many functions of `IterableMixing` assume that you have a property `items`, which is what defines a `BaseIterable`. Does this make sense?

**Comment by aiola** [comment]
Yes, sure, `IterableUtilsMixin` does assume the `items` property. In C++ we would use templated inheritance to comply with static type checking. In python there are no templates. We could make `IterableUtilsMixin` extend `BaseIterable`, but I think it is not a good idea. The issue is that you can easily mess things up by changing the order of the inheritance tree.
Currently you can do:

```
class CachedDocuments(IterableUtilsMixin[Document, LazyDocument, CachedDocument], CachedIterable[Document]):
    ...
```

or

```
class CachedDocuments(CachedIterable[Document], IterableUtilsMixin[Document, LazyDocument, CachedDocument]):
    ...
```

Both versions work fine. However, if `IterableUtilsMixin` extends `BaseIterable` the first version will not work because the MRO (method resolution order) gives priority to the `items` definition of the first parent class.
